/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDonationsIndexRouteImport } from './routes/_authenticated/donations.index'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions.$id'
import { Route as AuthenticatedMaterialsIdRouteImport } from './routes/_authenticated/materials.$id'
import { Route as AuthenticatedDonationsNewRouteImport } from './routes/_authenticated/donations.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonationsIndexRoute =
  AuthenticatedDonationsIndexRouteImport.update({
    id: '/donations/',
    path: '/donations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedMaterialsIdRoute =
  AuthenticatedMaterialsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMaterialsRoute,
  } as any)
const AuthenticatedDonationsNewRoute =
  AuthenticatedDonationsNewRouteImport.update({
    id: '/donations/new',
    path: '/donations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/donations/new': typeof AuthenticatedDonationsNewRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/donations/': typeof AuthenticatedDonationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/donations/new': typeof AuthenticatedDonationsNewRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/donations': typeof AuthenticatedDonationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/_authenticated/donations/new': typeof AuthenticatedDonationsNewRoute
  '/_authenticated/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/_authenticated/donations/': typeof AuthenticatedDonationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/materials'
    | '/profile'
    | '/reports'
    | '/transactions'
    | '/donations/new'
    | '/materials/$id'
    | '/transactions/$id'
    | '/donations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/materials'
    | '/profile'
    | '/reports'
    | '/transactions'
    | '/donations/new'
    | '/materials/$id'
    | '/transactions/$id'
    | '/donations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/materials'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/transactions'
    | '/_authenticated/donations/new'
    | '/_authenticated/materials/$id'
    | '/_authenticated/transactions/$id'
    | '/_authenticated/donations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donations/': {
      id: '/_authenticated/donations/'
      path: '/donations'
      fullPath: '/donations/'
      preLoaderRoute: typeof AuthenticatedDonationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/materials/$id': {
      id: '/_authenticated/materials/$id'
      path: '/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof AuthenticatedMaterialsIdRouteImport
      parentRoute: typeof AuthenticatedMaterialsRoute
    }
    '/_authenticated/donations/new': {
      id: '/_authenticated/donations/new'
      path: '/donations/new'
      fullPath: '/donations/new'
      preLoaderRoute: typeof AuthenticatedDonationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMaterialsRouteChildren {
  AuthenticatedMaterialsIdRoute: typeof AuthenticatedMaterialsIdRoute
}

const AuthenticatedMaterialsRouteChildren: AuthenticatedMaterialsRouteChildren =
  {
    AuthenticatedMaterialsIdRoute: AuthenticatedMaterialsIdRoute,
  }

const AuthenticatedMaterialsRouteWithChildren =
  AuthenticatedMaterialsRoute._addFileChildren(
    AuthenticatedMaterialsRouteChildren,
  )

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
  AuthenticatedDonationsNewRoute: typeof AuthenticatedDonationsNewRoute
  AuthenticatedDonationsIndexRoute: typeof AuthenticatedDonationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
  AuthenticatedDonationsNewRoute: AuthenticatedDonationsNewRoute,
  AuthenticatedDonationsIndexRoute: AuthenticatedDonationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
